version: 1.0
os: linux
files:
    - source: /
      destination: /home/ec2-user/bottenanna
permissions:
  #  - object: /var/www/html
  #    pattern: "**"
  #    owner: apache
  #    group: apache
  #    mode: 755
  #    type:
  #      - file
hooks:
  #  BeforeInstall:
  #   - location: scripts/before.sh
  #     timeout: 300
  #     runas: ec2-user

  AfterInstall:
    - location: scripts/after.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user